INSERT INTO ANJANA.BOOK_DETAIL (BOOK_ID, AUTHOR, PUBLISHER) VALUES (2, 'Lewis Carroll', 'Macmillan Publishers');
INSERT INTO ANJANA.BOOK_DETAIL (BOOK_ID, AUTHOR, PUBLISHER) VALUES (3, 'Rick Riordan', 'Hyperion');
INSERT INTO ANJANA.BOOK_DETAIL (BOOK_ID, AUTHOR, PUBLISHER) VALUES (4, 'XYZ', 'Usborne');
INSERT INTO ANJANA.BOOK_DETAIL (BOOK_ID, AUTHOR, PUBLISHER) VALUES (101, 'JK Rowling', 'Bloomsburry');